apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: pre
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/managed-by: Helm
data:
  alerting_rules.yml: |
    {}

  alerts: |
    {}

  allow-snippet-annotations: "false"

  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "pre-app"
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ["pre-app:8000"]

  recording_rules.yml: |
    {}

  rules: |
    {}

